//! world implementation modules.
pub(in crate::renderer) mod bindings;
pub(in crate::renderer) mod detail_textures;
pub(in crate::renderer) mod draw;
pub(in crate::renderer) mod geometry;
pub(in crate::renderer) mod inline_models;
pub(in crate::renderer) mod lifecycle;
pub(in crate::renderer) mod pipelines;
pub(in crate::renderer) mod settings;
pub(in crate::renderer) mod types;
pub(in crate::renderer) mod upload;
pub(in crate::renderer) mod variants;
pub(in crate::renderer) mod videos;
