//! lighting implementation modules.
pub(in crate::renderer) mod cascades;
pub(in crate::renderer) mod entity_shadows;
pub(in crate::renderer) mod legacy_dlights;
pub(in crate::renderer) mod local_shadows;
pub(in crate::renderer) mod ray_tracing;
pub(in crate::renderer) mod settings;
pub(in crate::renderer) mod shadow_resources;
pub(in crate::renderer) mod state;
pub(in crate::renderer) mod sun;
pub(in crate::renderer) mod upload;
